name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest pytest-cov || true

      - name: Lint (flake8)
        run: |
          if [ -d src ]; then flake8 src; else flake8 .; fi

      - name: Tests (pytest)
        run: |
          if [ -d tests ]; then pytest -q; else echo "No tests yet"; fi
